
      var strVar="";
          strVar += "<div class=\"table\">";
          strVar += "                                <div class=\"cool-facts\">";
          strVar += "                                    <span class=\"cool-facts-title\">Cool Facts<\/span><img class=\"creative-icons\" src='creative.png' alt=\"creative\" \/>";
          strVar += "                                    <hr \/>";
          strVar += "                                    <div class=\"facts\">";
          strVar += "                                        <ul>";
          strVar += "                                            <li style={{lineHeight: '1.8'}}>";
          strVar += "                                                 Southbury IBM is the largest corporate complex in Southbury";
          strVar += "                                            <\/li>";
          strVar += "                                             <br \/>";
          strVar += "                                            <li style={{lineHeight: '1.8'}}>";
          strVar += "                                                 Remade its old cafeteria into a new agile space which opened the summer of 2018";
          strVar += "                                            <\/li>";
          strVar += "                                        <\/ul>";
          strVar += "                                    <\/div>";
          strVar += "                                <\/div>";
          strVar += "                                <div class=\"events\">";
          strVar += "                                    <hr \/>";
          strVar += "                                    <span class=\"events-title\">Weekly Events<\/span><img class=\"weekly-icons\" src='calendar.png' alt=\"calendar\" \/>";
          strVar += "                                    <hr \/>";
          strVar += "                                    <ul class=\"weekly-events\">";
          strVar += "                                        <li>Yoga Mondays <img class=\"weekly-icons\" src='exercise.png' alt=\"yoga\" \/><\/li>";
          strVar += "                                        <li>BBQ Tuesdays <img class=\"weekly-icons\" src='spatula.png' alt=\"bbq\" \/><\/li>";
          strVar += "                                        <li>Soccer Wednesdays <img class=\"weekly-icons\" src='football.png' alt=\"soccer\" \/><\/li>";
          strVar += "                                        <li>Ping Pong Thursdays <img class=\"weekly-icons\" src='ping-pong.png' alt=\"ping\" \/><\/li>";
          strVar += "                                        <li>Movie Fridays <img class=\"weekly-icons\" src='video-camera.png' alt=\"movie\" \/><\/li>";
          strVar += "                                    <\/ul>";
          strVar += "                                <\/div>";
          strVar += "                                <div class=\"trips\">";
          strVar += "                                    <hr \/>";
          strVar += "                                    <span class=\"trips-title\">IBM Trips<\/span><img class=\"vacation-icons\" src='sunset.png' alt=\"vacation\" \/>";
          strVar += "                                    <hr \/>";
          strVar += "                                    <iframe ";
          strVar += "                                        src=\"https:\/\/snapwidget.com\/embed\/716192\"   ";
          strVar += "                                        allowtransparency=\"true\" ";
          strVar += "                                        frameborder=\"0\" ";
          strVar += "                                        scrolling=\"no\" ";
          strVar += "                                        class=\"ig-slideshow\">";
          strVar += "                                    <\/iframe>";
          strVar += "                                <\/div>";
          strVar += "                                ";
          strVar += "                                <div>";
          strVar += "                                    <a ";
          strVar += "                                        href=\"https:\/\/twitter.com\/intent\/tweet?button_hashtag=ibmatsouthbury&ref_src=twsrc%5Etfw\" ";
          strVar += "                                        target=\"_blank\"";
          strVar += "                                        class=\"twitter-hashtag-button\" ";
          strVar += "                                        data-show-count=\"false\">Tweet #ibmatsouthbury";
          strVar += "                                    <\/a>";
          strVar += "                                    <script async src=\"https:\/\/platform.twitter.com\/widgets.js\" charSet=\"utf-8\"><\/script>";
          strVar += "                                <\/div>";
          strVar += "                                <div class=\"social-media\">";
          strVar += "                                    <h1 class=\"social-media-title\">Follow us @Social Media<\/h1>";
          strVar += "                                    <div class=\"icon-row\">";
          strVar += "                                        <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https:\/\/www.instagram.com\/lifeatibmsouthbury\/\">";
          strVar += "                                            <img class=\"icons\"  src='instagram.png' alt=\"ig\"\/>";
          strVar += "                                        <\/a>";
          strVar += "                                        <img class=\"icons\" src='snapcode.png' alt=\"snapcode\" \/>";
          strVar += "                                        <a target=\"_blank\" rel=\"noopener noreferrer\" href=\"https:\/\/twitter.com\/ibmatsouthbury\">";
          strVar += "                                            <img class=\"icons\"  src='twitter.png' alt=\"twitter\"\/>";
          strVar += "                                        <\/a>";
          strVar += "                                    <\/div>";
          strVar += "                                <\/div>";
          strVar += "                                 <div>";
          strVar += "                                    <a ";
          strVar += "                                        target=\"_blank\" ";
          strVar += "                                        class=\"join-now\"";
          strVar += "                                        rel=\"noopener noreferrer\" ";
          strVar += "                                        href=\"https:\/\/careers.ibm.com\/ListJobs\/All\/Search\/jobtitle\/intern\/country\/us\/\"> ";
          strVar += "                                    Join Us Now";
          strVar += "                                    <\/a>";
          strVar += "                                <\/div>";